{{- $fullName := include "..fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "..fullname" . }}
data:
  wechat.yaml: |-
    token: {{ .Values.wechat.token }}
    git_url: {{ .Values.wechat.gitURL }}
    git_branch: {{ .Values.wechat.gitBranch }}
    github_webhook_secret: {{ .Values.wechat.gitHubSecret }}
    server_port: {{ .Values.service.port }}
